namespace AST_new;

public partial class DatatypeConstructorDecl : MemberDecl { }
public partial class DatatypeDestructorDecl : FieldDecl { }
public partial class DatatypeDiscriminatorDecl : FieldDecl { }

public partial class DatatypeConstructorDecl : MemberDecl {
  public override string Name { get; protected set; }
  public readonly List<Formal> Formals = new();

  public DatatypeConstructorDecl(DatatypeDecl enclosingDecl,
  string name, IEnumerable<Formal>? formals = null)
  : base(enclosingDecl) {
    Name = name;
    if (formals != null) {
      Formals.AddRange(formals);
    }
  }

}

// This is an autogenerated declaration that should not be printed.
public partial class DatatypeDestructorDecl : FieldDecl {
  // Within the same datatype, fields of the same name and type within different 
  // constructors share the same destructor.
  // public Dictionary<DatatypeConstructorDecl, Formal> Destructors = new();

  public DatatypeDestructorDecl(TopLevelDecl enclosingDecl,
  string name, Type type)
  : base(enclosingDecl, name, type) { }

  public DatatypeDestructorDecl(TopLevelDecl enclosingDecl,
  Formal constructorFormal)
  : this(enclosingDecl, constructorFormal.Name, constructorFormal.Type) { }
}

// This is an autogenerated declaration that should not be printed.
public partial class DatatypeDiscriminatorDecl : FieldDecl {
  public DatatypeDiscriminatorDecl(TopLevelDecl enclosingDecl,
  string constructorName)
  : base(enclosingDecl, constructorName + "?", Type.Bool) { }

  public DatatypeDiscriminatorDecl(DatatypeConstructorDecl constructor)
  : this(constructor.EnclosingDecl, constructor.Name) { }
}
