namespace AST.Cloner;

public partial class ASTCloner {
  private Expression CloneExpression(Expression e) {
    return e switch {
      LiteralExpr le => CloneLiteralExpr(le),
      IdentifierExpr ie => CloneIdentifierExpr(ie),
      ParensExpr pe => CloneParensExpr(pe),
      BinaryExpr be => CloneBinaryExpr(be),
      UnaryExpr ue => CloneUnaryExpr(ue),
      MemberSelectExpr me => CloneMemberSelectExpr(me),
      CollectionElementExpr ce => CloneCollectionSelectExpr(ce),
      CollectionSliceExpr ce => CloneCollectionSelectExpr(ce),
      SeqDisplayExpr se => CloneCollectionDisplayExpr(se),
      SetDisplayExpr se => CloneCollectionDisplayExpr(se),
      MultiSetDisplayExpr me => CloneCollectionDisplayExpr(me),
      MapDisplayExpr me => CloneCollectionDisplayExpr(me),
      SetComprehensionExpr se => CloneComprehensionExpr(se),
      MapComprehensionExpr me => CloneComprehensionExpr(me),
      CollectionUpdateExpr ce => CloneCollectionUpdateExpr(ce),
      MultiSetConstructionExpr me => CloneMultiSetConstructionExpr(me),
      SeqConstructionExpr se => CloneSeqConstructionExpr(se),
      DatatypeValueExpr de => CloneDatatypeValueExpr(de),
      ThisExpr te => CloneThisExpr(te),
      AutoGeneratedExpr ae => CloneAutoGeneratedExpr(ae),
      WildcardExpr we => CloneWildcardExpr(we),
      FunctionCallExpr fe => CloneFunctionCallExpr(fe),
      StaticReceiverExpr se => CloneStaticReceiverExpr(se),
      ITEExpr ite => CloneITEExpr(ite),
      LetExpr le => CloneLetExpr(le),
      QuantifierExpr qe => CloneQuantifierExpr(qe),
      MatchExpr me => CloneMatchExpr(me),
      LambdaExpr le => CloneLambdaExpr(le),
      DatatypeUpdateExpr de => CloneDatatypeUpdateExpr(de),
      _ => throw new UnsupportedNodeCloningException(e),
    };
  }

  private LiteralExpr CloneLiteralExpr(LiteralExpr e) {
    return e switch {
      BoolLiteralExpr be => new BoolLiteralExpr(be.Value),
      CharLiteralExpr ce => new CharLiteralExpr(ce.Value),
      IntLiteralExpr ie => new IntLiteralExpr(ie.Value),
      RealLiteralExpr re => new RealLiteralExpr(re.Value),
      StringLiteralExpr se => new StringLiteralExpr(se.Value),
      NullLiteralExpr ne => new NullLiteralExpr(CloneType(ne.Type)),
      _ => throw new UnsupportedNodeCloningException(e),
    };
  }

  private IdentifierExpr CloneIdentifierExpr(IdentifierExpr e) {
    return new IdentifierExpr(CloneVariable(e.Var));
  }

  private ParensExpr CloneParensExpr(ParensExpr e) {
    return new ParensExpr(CloneExpression(e.E));
  }

  private BinaryExpr CloneBinaryExpr(BinaryExpr e) {
    return new BinaryExpr(e.Op, CloneExpression(e.E0), CloneExpression(e.E1));
  }

  private UnaryExpr CloneUnaryExpr(UnaryExpr e) {
    return new UnaryExpr(e.Op, CloneExpression(e.E));
  }

  private MemberSelectExpr CloneMemberSelectExpr(MemberSelectExpr e) {
    return new MemberSelectExpr(
      CloneExpression(e.Receiver), (MemberDecl)CloneDeclRef(e.Member));
  }

  private CollectionElementExpr CloneCollectionSelectExpr(CollectionElementExpr e) {
    return new CollectionElementExpr(
      CloneExpression(e.Collection), CloneExpression(e.Index));
  }

  private CollectionSliceExpr CloneCollectionSelectExpr(CollectionSliceExpr e) {
    return new CollectionSliceExpr(CloneExpression(e.Collection),
      e.Index0 == null ? null : CloneExpression(e.Index0),
      e.Index1 == null ? null : CloneExpression(e.Index1));
  }

  private SeqDisplayExpr CloneCollectionDisplayExpr(SeqDisplayExpr e) {
    return new SeqDisplayExpr(e.Elements.Select(CloneExpression));
  }

  private SetDisplayExpr CloneCollectionDisplayExpr(SetDisplayExpr e) {
    return new SetDisplayExpr(e.Elements.Select(CloneExpression));
  }

  private MultiSetDisplayExpr CloneCollectionDisplayExpr(MultiSetDisplayExpr e) {
    return new MultiSetDisplayExpr(e.Elements.Select(CloneExpression));
  }

  private MapDisplayExpr CloneCollectionDisplayExpr(MapDisplayExpr e) {
    return new MapDisplayExpr(e.Elements.Select(CloneExpressionPair));
  }

  private SetComprehensionExpr CloneComprehensionExpr(SetComprehensionExpr e) {
    return new SetComprehensionExpr(CloneQuantifierDomain(e.QuantifierDomain),
      e.Value == null ? null : CloneExpression(e.Value));
  }

  private MapComprehensionExpr CloneComprehensionExpr(MapComprehensionExpr e) {
    return new MapComprehensionExpr(CloneQuantifierDomain(e.QuantifierDomain),
      e.Key == null ? null : CloneExpression(e.Key), CloneExpression(e.Value));
  }

  private CollectionUpdateExpr CloneCollectionUpdateExpr(CollectionUpdateExpr e) {
    return new CollectionUpdateExpr(CloneExpression(e.Collection),
      CloneExpression(e.Index), CloneExpression(e.Value));
  }

  private MultiSetConstructionExpr CloneMultiSetConstructionExpr(MultiSetConstructionExpr e) {
    return new MultiSetConstructionExpr(CloneExpression(e.E));
  }

  private SeqConstructionExpr CloneSeqConstructionExpr(SeqConstructionExpr e) {
    return new SeqConstructionExpr(
      CloneExpression(e.Count), CloneExpression(e.Initialiser));
  }

  private DatatypeValueExpr CloneDatatypeValueExpr(DatatypeValueExpr e) {
    return new DatatypeValueExpr(
      (DatatypeConstructorDecl)CloneDeclRef(e.Constructor),
      e.ConstructorArguments.Select(CloneExpression));
  }

  private ThisExpr CloneThisExpr(ThisExpr e) {
    var type = CloneType(e.Type);
    if (e is ImplicitThisExpr) {
      return new ImplicitThisExpr(type);
    }
    return new ThisExpr(type);
  }

  private AutoGeneratedExpr CloneAutoGeneratedExpr(AutoGeneratedExpr e) {
    return new AutoGeneratedExpr(CloneExpression(e.E));
  }

  private WildcardExpr CloneWildcardExpr(WildcardExpr e) {
    return new WildcardExpr();
  }

  private FunctionCallExpr CloneFunctionCallExpr(FunctionCallExpr e) {
    return new FunctionCallExpr(
      CloneExpression(e.Callee), e.Arguments.Select(CloneExpression));
  }

  private StaticReceiverExpr CloneStaticReceiverExpr(StaticReceiverExpr e) {
    var d = (TopLevelDecl)CloneDeclRef(e.Decl);
    if (e is ImplicitStaticReceiverExpr) {
      return new ImplicitStaticReceiverExpr(d);
    }
    return new StaticReceiverExpr(d);
  }

  private ITEExpr CloneITEExpr(ITEExpr e) {
    return new ITEExpr(CloneExpression(e.Guard),
      CloneExpression(e.Thn), CloneExpression(e.Els));
  }

  private LetExpr CloneLetExpr(LetExpr e) {
    return new LetExpr(e.Vars.Select(v =>
      new KeyValuePair<BoundVar, Expression>(
        CloneBoundVar(v.Key), CloneExpression(v.Value))),
      CloneExpression(e.Body));
  }

  private QuantifierExpr CloneQuantifierExpr(QuantifierExpr e) {
    var qd = CloneQuantifierDomain(e.QuantifierDomain);
    var term = CloneExpression(e.Term);
    if (e is ForallExpr) {
      return new ForallExpr(qd, term);
    } else if (e is ExistsExpr) {
      return new ExistsExpr(qd, term);
    } else {
      throw new UnsupportedNodeCloningException(e);
    }
  }

  private MatchExpr CloneMatchExpr(MatchExpr e) {
    return new MatchExpr(
      CloneExpression(e.Selector), e.Cases.Select(CloneMatchExprCase));
  }

  private LambdaExpr CloneLambdaExpr(LambdaExpr e) {
    return new LambdaExpr(
      params_: e.Params.Select(CloneBoundVar),
      result: CloneExpression(e.Result),
      pre: CloneSpecification(e.Precondition),
      reads: CloneSpecification(e.ReadFrame));
  }

  private DatatypeUpdateExpr CloneDatatypeUpdateExpr(DatatypeUpdateExpr e) {
    return new DatatypeUpdateExpr(CloneExpression(e.DatatypeValue),
      e.Updates.Select(CloneDatatypeUpdatePair));
  }

}
