namespace AST_new;

public abstract partial class Expression : Node {
  public virtual Type Type {
    get => throw new UnsupportedASTOperationException(this,
      "expression type retrieval");
  }
}

public partial class ParensExpr : Expression {
  public Expression E { get; set; }
  public override Type Type => E.Type;

  public ParensExpr(Expression e) {
    E = e;
  }

  public override IEnumerable<Node> Children => new[] { E };
}

public partial class AutoGeneratedExpr : Expression {
  public Expression E { get; set; }
  public override Type Type => E.Type;

  public AutoGeneratedExpr(Expression e) {
    E = e;
  }

  public override IEnumerable<Node> Children => new[] { E };
}

public partial class WildcardExpr : Expression {
  public override IEnumerable<Node> Children => Enumerable.Empty<Node>();
}
