namespace AST;

// Expressions that are not derived from the program text.
// AutoGeneratedExpressions may originate from e.g. clause inference.
public class AutoGeneratedExpression
: ParensExpression, ConstructableFromDafny<Dafny.AutoGeneratedExpression, AutoGeneratedExpression> {
  private AutoGeneratedExpression(Dafny.AutoGeneratedExpression autoGenExprDafny)
  : base(autoGenExprDafny) { }

  public static AutoGeneratedExpression FromDafny(Dafny.AutoGeneratedExpression dafnyNode) {
    return new AutoGeneratedExpression(dafnyNode);
  }
}
