namespace AST;

public class ParensExpression
: Expression, ConstructableFromDafny<Dafny.ParensExpression, ParensExpression> {
  public Expression E { get; set; }

  protected ParensExpression(Dafny.ParensExpression parensExprDafny) {
    E = Expression.FromDafny(parensExprDafny.E);
  }

  public static ParensExpression FromDafny(Dafny.ParensExpression dafnyNode) {
    if (dafnyNode is Dafny.AutoGeneratedExpression ageDafny) {
      return AutoGeneratedExpression.FromDafny(ageDafny);
    }
    return new ParensExpression(dafnyNode);
  }
}
