namespace AST;

public class ParensExpression
: Expression, ConstructableFromDafny<Dafny.ParensExpression, ParensExpression> {
  public override IEnumerable<Node> Children => new Node[] { E };

  public Expression E { get; set; }
  public override Type Type { get => E.Type; }

  public ParensExpression(Expression E) {
    this.E = E;
  }

  protected ParensExpression(Dafny.ParensExpression parensExprDafny)
  : this(Expression.FromDafny(parensExprDafny.E)) { }

  public static ParensExpression FromDafny(Dafny.ParensExpression dafnyNode) {
    if (dafnyNode is Dafny.AutoGeneratedExpression ageDafny) {
      return AutoGeneratedExpression.FromDafny(ageDafny);
    }
    return new ParensExpression(dafnyNode);
  }
}
